classdef calculateExtremePathwaysTest < matlab.unittest.TestCase

    methods (Test)
        function testCalculateExtremePathwaysOrdBiBiInhib(testCase)
            Selem = [1     1     0     0     0    -1; ...
                     -1     0     1     0     0     0; ...
                      0    -1     0     0     0     0; ...
                      0     0    -1     1     0     0; ...
                      0     0     0    -1     1     0; ...
                      0     0     0     0    -1     1];
            [extremePath] = calculateExtremePathways(Selem);
            
            trueResExtremePath = [1; 0; 1; 1; 1; 1];
   
            testCase.verifyEqual(trueResExtremePath,extremePath);            
            
        end
        
        function testCalculateExtremePathwaysOrdBiBi(testCase)
            Selem = [1     0     0     0    -1; ...
                    -1     1     0     0     0; ...
                     0    -1     1     0     0; ...
                     0     0    -1     1     0; ...
                     0     0     0    -1     1];
                 
            [extremePath] = calculateExtremePathways(Selem);
            
            trueResExtremePath = [1; 1; 1; 1; 1];
   
            testCase.verifyEqual(trueResExtremePath,extremePath);            
            
        end
        
         function testCalculateExtremePathwaysOrdBiBiInhibPromiscuous(testCase)
            Selem = [1     0     0     0     0    -1     1     0     0     0     0    -1; ...
                    -1     1     1     0     0     0     0     0     0     0     0     0; ...
                     0    -1     0     0     0     0     0     0     0     0     0     0; ...
                     0     0    -1     1     0     0     0     0     0     0     0     0; ...
                     0     0     0    -1     1     0     0     0     0     0     0     0; ...
                     0     0     0     0    -1     1     0     0     0     0     0     0; ...
                     0     0     0     0     0     0    -1     1     1     0     0     0; ...
                     0     0     0     0     0     0     0    -1     0     0     0     0; ...
                     0     0     0     0     0     0     0     0    -1     1     0     0; ...
                     0     0     0     0     0     0     0     0     0    -1     1     0; ...
                     0     0     0     0     0     0     0     0     0     0    -1     1];
            [extremePath] = calculateExtremePathways(Selem);
            
            trueResExtremePath = [ 1     0;...
                                   0     0;...
                                   1     0;...
                                   1     0;...
                                   1     0;...
                                   1     0;...
                                   0     1;...
                                   0     0;...
                                   0     1;...
                                   0     1;...
                                   0     1;...
                                   0     1];
   
            testCase.verifyEqual(trueResExtremePath,extremePath);            
            
        end
        
    end
end

